---
- name: "Commit pending..."
  shell: |
    etckeeper commit "Ansible commit all..."
    exit 0

- name: "Install Apt repository"
  include_tasks: Debian.yml
  when: "'.deb' not in ossec_agent_package_name"

- name: "Install {{ ossec_agent_package_name }}"
  apt:
    name: "{{ ossec_agent_package_name }}"
    force: yes
    update_cache: yes
  when: "'.deb' not in ossec_agent_package_name and ansible_os_family == 'Debian'"

- name: Install OSSEC Agent from .deb package
  apt: deb="{{ ossec_agent_package_name }}"
  when: "'.deb' in ossec_agent_package_name and ansible_distribution_release == 'wheezy'"

- name: "Install Yum repository"
  include_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Set ossec deploy facts for RedHat
  set_fact:
    ossec_agent_config_filename: ossec-agent.conf
    ossec_init_name: ossec-hids
  when: ansible_os_family == "RedHat"

- name: Set ossec deploy facts for Debian
  set_fact:
    ossec_agent_config_filename: ossec.conf
    ossec_init_name: ossec
  when: ansible_os_family == "Debian"

- name: Finding running service...
  include_tasks: Service.yml

- name: "Installing ossec-agent.conf default"
  template:
    src: var-ossec-etc-ossec-agent.conf.j2
    dest: /var/ossec/etc/{{ ossec_agent_config_filename }}
    owner: root
    group: root
    mode: 0644
  notify: restarted ossec-agent
  when: service.stdout == ""

- name: "Check if client.keys exists"
  stat:
    path: /var/ossec/etc/client.keys
  register: check_keys
  tags:
    - config

- name: "Check if client.keys exists on ossec-server"
  stat:
    path: /var/ossec/etc/client.keys
  when: ossec_managed_server
  delegate_to: "{{ ossec_server_name }}"
  register: check_server_keys
  tags:
    - config

- name: Set Ossim server to intrantet
  set_fact:
    ossec_server_ip: 10.0.2.2
  when: "'.server.domain.com' in inventory_hostname"

- name: "register client"
  shell: "/var/ossec/bin/agent-auth -m {{ ossec_server_ip|default(ossec_server_fqdn) }} -p 1515 -A '{{ ossec_agent_name|default(ansible_hostname) }}'"
  args:
    creates: /var/ossec/etc/client.keys
  tags:
    - config
    - skip_ansible_lint

- name: Set permissions on client.keys file
  file:
    dest: /var/ossec/etc/client.keys
    mode: 0640

- name: "Start ossec-agent if not already running"
  service:
    name: "{{ ossec_init_name }}"
    state: restarted
    enabled: yes

- name: "Commit pending..."
  shell: |
    etckeeper commit "Ansible commit all..."
    exit 0
